export const obj = {
  amygdalase: {
    peacemaking: [
      65, 2016, 5251, 7071, 5726, 3325, 9893, 1547, 1409, 6715, 3656, 6780, 1460, 521, 3103, 6618, 9433, 3056, 70, 4967, 3641, 6013, 9235,
      1163, 1117, 4493, 1464, 4278, 4714, 4520, 7763, 2937, 4418, 1613, 8941, 7429, 7766, 5482, 9928, 3749, 4625, 1975, 4595, 3458
    ],
    housewifeliness: [
      'freezer',
      'hield',
      'inaxon',
      'philophilosophos',
      'Saturnalian',
      'celery',
      'forsooth',
      'nirles',
      'duteous',
      'gastrohelcosis',
      'hateful',
      'exalate',
      'scowlingly',
      'thoracoscopy',
      'glossophagine',
      'informative',
      'indignance',
      'ophthalmomalacia'
    ],
    baller: [
      4497, 4151, 7362, 3155, 1098, 9372, 922, 5132, 8717, 1053, 9654, 6451, 9894, 8481, 2487, 545, 6062, 1350, 1321, 9695, 7783, 6100,
      6511, 4994, 6873, 5105, 3804, 4896
    ],
    heterochronic: [
      'somniloquy',
      'interenjoy',
      'vastity',
      'abdominous',
      'nonimmigrant',
      'verbomania',
      'hexastemonous',
      'hoyle',
      'plicater',
      'hygrodeik',
      'niellated',
      'extrafoliaceous',
      'precursive'
    ],
    reamer: [
      true,
      false,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      true,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      true,
      false,
      true,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      true,
      false,
      true,
      false
    ]
  },
  apagogically: {
    troolie: {
      preponderance: 'aischrolatreia',
      warison: 'hydrocycle',
      meteorogram: 6608,
      nonporphyritic: 344,
      scelerat: 5669,
      rumorproof: true,
      garawi: 'adactyl',
      stythe: 8681,
      primitivism: 'unenforcedly',
      conjunct: false,
      schistaceous: 'kilocycle',
      anthropophagistic: 'seedbox',
      treacliness: 'ratable'
    },
    treader: {
      evangelary: 'rattlingly',
      capersome: 'columnization',
      saturator: true,
      forthwith: 4799,
      metachemistry: true,
      velours: 6616,
      dulcifluous: 'spinobulbar',
      wildness: 'Sid'
    },
    Jeremian: {
      probeer: 'bombastic',
      ratable: 9483,
      pharyngotonsillitis: 6876,
      homosystemic: 9566,
      notarikon: 2254,
      fiduciary: 149,
      nextly: true,
      flanched: 1280,
      Decimus: 1492,
      humpback: 'Kaibartha'
    },
    koolah: {
      kettledrummer: false,
      precondemnation: 750,
      koolah: 'Madelon',
      deferment: 'goatlike',
      unequated: true,
      nonporphyritic: 3289,
      azo: 'snary',
      ringe: 7921,
      preindication: false,
      synactic: false,
      propaedeutical: 6406,
      glossophagine: 'intermenstruum',
      warison: 3400,
      unagile: 6689,
      undisputed: 'Chaetophoraceae'
    },
    bombastic: {
      psychoanalyzer: 846,
      ovoviviparously: false,
      dilatingly: 5447,
      capersome: 'subglacially',
      dihydroxy: 'bufonite'
    },
    themeless: {
      ironback: false,
      unpleadable: 5189,
      unequated: true,
      licentiate: 5613,
      collyrium: 'toolmark',
      acquisitum: 'poststertorous',
      scorching: 8498,
      reamer: 'opusculum'
    },
    nonpresbyter: {
      evincement: true,
      lemography: 39,
      perfervidness: 'perceptive',
      bizet: 'os',
      adenia: 'nonconcludent',
      commenceable: true,
      unprejudicial: 'kala',
      brachypyramid: 6422,
      Taal: true
    },
    telemetric: {
      dermobranchiata: 'unwounded',
      sigillarian: true,
      unrhymed: 5319,
      extratension: 'Tatary',
      unbeing: false,
      enfeeble: 'heterochronic',
      mutinously: 'exalate',
      proferment: 'Mil'
    },
    hendecoic: {
      confederationist: false,
      nonporphyritic: 'presumptuous'
    },
    foremasthand: {
      Idiosepiidae: true,
      primitivism: 'prewound',
      lifey: 8926,
      untastable: 9821,
      nirles: false,
      vestal: true,
      introductoriness: 'ventripotential',
      empyrean: 'Honduran',
      glottiscope: 5663,
      oncin: 3319,
      Phalarism: 5195,
      sniffly: 'glycogelatin',
      subglacially: false,
      zwitterionic: false
    }
  },
  ratable: {
    forsooth: {
      dredge: true,
      overhover: true,
      force: 'Octavian',
      mandelic: true,
      endosalpingitis: 'Kaibartha',
      dermobranchiata: 'reactivity',
      rampire: 'esophagotomy',
      hield: 4808,
      outferret: false,
      ethnize: false,
      plumbum: 4434
    },
    inconvertibility: {
      pobs: 'keratocentesis',
      Saturnalian: true,
      loaferish: false,
      overhover: 4857,
      antimycotic: true,
      aweary: 7619,
      Elaps: true,
      conjunct: false,
      unchapter: 8078,
      overdevotedly: 'Octogynia',
      gold: 'ayelp',
      Mackinaw: 4912,
      trepidatory: 4402,
      Lin: false,
      breaker: 9271
    },
    unenforcedly: {
      foundery: false,
      ninut: 5313,
      principalness: 3857,
      asclepiadeous: false,
      hierogrammatical: true,
      glossophagine: true,
      louse: 'pleocrystalline'
    },
    tipstaff: {
      capersome: 6136,
      spydom: 'garawi',
      epicranial: 8284,
      scenic: 'spydom',
      angiolith: true,
      novelwright: 'basos',
      asphalt: false,
      rumorproof: 'natricine',
      confederationist: false
    },
    Saturnalian: {
      roominess: 'stomachlessness',
      hammy: false,
      comicocynical: true,
      proctoclysis: false,
      caravan: 1042,
      uncompassionate: 6828,
      undetermination: 6473,
      personalism: 8747,
      tupanship: true,
      ganglioid: 'subarmor',
      gold: false,
      Blackbeard: true
    },
    bombastic: {
      unequated: 'loaferish',
      fitchee: 'discontinuee',
      dilatingly: 'Pentelic',
      fusible: 'scoliotic',
      rollickingness: 'tribase',
      atamasco: 'unhero',
      hysteric: true,
      intenable: false,
      barbiturate: false,
      dacryocystotomy: false
    },
    underact: {
      acroasphyxia: 'ludefisk',
      principalness: 'Sisseton',
      lampers: 'Pygopodidae',
      purchase: 1843
    },
    complacent: {
      hateful: 7358,
      trapped: false,
      dulcifluous: true,
      supersympathy: false,
      Caesardom: 'anatomicopathologic',
      bitterroot: 3375,
      epigenetic: true,
      macrosymbiont: 1817,
      noncarnivorous: false,
      transversomedial: 'lovelorn'
    },
    distasteful: {
      enfeeble: false,
      cyanidation: 'tech',
      iceland: 5707,
      natricine: false,
      deiformity: 'toying',
      archheart: 'milliare',
      adenology: 6315,
      ruck: 4703,
      hateful: 'urrhodin',
      koku: true,
      annodated: 'unenforcedly'
    },
    anaphylatoxin: {
      congressionist: 'echinodermic',
      slackerism: true,
      guijo: 102,
      macrospore: 3789,
      unjagged: true
    },
    Lecanium: {
      ichthyotomy: 'Dardistan',
      flatwise: false,
      semisocial: 6342,
      poststertorous: true,
      nonumbilicate: 9668,
      slackerism: 'preaffiliation'
    },
    hendecoic: {
      pitchometer: 'fanon',
      amateur: 'cyanidation',
      amylopsin: false,
      urethrorrhea: 'baseball',
      nonconcludent: 5458,
      imitability: 3953,
      preindication: 6644,
      helvite: 7318,
      humpback: false,
      planarioid: true,
      Rajah: false,
      Caesardom: 'kelty'
    },
    eellike: {
      menorrhagia: 'zygozoospore',
      nonliability: false
    },
    fibroplastic: {
      sensationistic: 'gradient',
      loaferish: 'Muncerian',
      caravan: 5761,
      supracaudal: 'glycogelatin',
      lovelorn: 7156,
      tarnside: true,
      Eumenes: 'foliature',
      marshwort: true
    }
  },
  microdrawing: {
    profanely: {
      abbot: 1295,
      recce: 8334,
      licentiate: 8441,
      trest: 7223,
      anaglyph: 9696,
      foundery: 2346,
      presbyopia: true
    },
    inconvertibility: {
      reputationless: 4969,
      porwigle: 8549,
      certifiableness: 4036,
      dolichocephali: 'unsurpassableness',
      eater: 6483,
      elderhood: true,
      soulfulness: 'sybaritism',
      oxbiter: true
    },
    torse: {
      siccity: true,
      coky: 'ludefisk',
      bellite: 'hypodorian',
      introductoriness: 9914,
      vesicupapular: 'duteous',
      pitchometer: true
    }
  },
  foremasthand: {
    extratension: [
      'garter',
      'Tanyoan',
      'outweary',
      'Bonapartism',
      'milliare',
      'lifey',
      'dubitatingly',
      'pobs',
      'Serridentines',
      'nirles',
      'hereby',
      'azo',
      'driblet',
      'imminution',
      'dacryocystotomy',
      'anaphylatoxin',
      'columnization',
      'heptitol',
      'tarnside',
      'Eumenes',
      'decoyer',
      'karyomitoic',
      'Mil',
      'Orobanche',
      'impalpably',
      'overeducate',
      'unsteck',
      'unclassable',
      'avowably',
      'zig',
      'extrafoliaceous',
      'torse',
      'antiprohibitionist',
      'unsurpassableness',
      'deiformity',
      'Dioecia',
      'septated',
      'underivable',
      'qualitied',
      'pharyngopathy',
      'trekker',
      'nerval',
      'outweary',
      'unbrotherliness',
      'optotechnics',
      'Mimulus',
      'unbumptious'
    ],
    Vaudois: [
      7957, 5096, 7055, 2466, 3607, 9716, 4551, 1242, 1696, 1959, 9440, 336, 100, 1779, 8773, 5649, 5566, 6192, 7976, 2831, 8144, 4551,
      5126, 1418, 6042, 9238, 8126, 6002, 3378, 3895, 1077, 8923, 6722, 4283, 5247, 6690
    ],
    poststertorous: [
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      false,
      false,
      false,
      true
    ],
    patterny: [false, false, false, false, false, true, true, true, true, true, false, false, true, false, false, true, true, true, false],
    song: [false, true, false, true, false, true, true, false, false, true, true, false, false, true, false],
    foremasthand: [2678],
    imitability: [true, false, false, true, true, true, false, true, false, false, true, true, false, false],
    blossomtime: [
      3723, 4953, 4357, 6191, 6279, 2718, 3840, 9782, 9849, 4709, 6551, 3556, 7043, 8956, 9994, 8354, 2066, 4068, 29, 9036, 3080, 4685,
      3241, 535, 8006, 5560, 6890, 171, 5815, 1163, 8467, 8600, 9241, 4086, 2229, 1629, 261, 8115
    ],
    scorching: [5401, 2243, 674, 5497, 8439, 2049, 2455, 2705, 6030, 7062, 1346, 9389, 6719, 9027, 5, 5598, 1494, 1162, 6208, 1951, 902],
    underivable: [false, true],
    ateleological: [
      'firetop',
      'hawserwise',
      'elaidinic',
      'psychoanalyzer',
      'unhandsome',
      'laryngoscopical',
      'wellington',
      'monochlor',
      'nystagmus',
      'gambet',
      'tech',
      'confederationist',
      'nonrendition',
      'diligentness',
      'unobjective'
    ],
    telson: [
      7067, 8002, 1302, 8268, 8182, 9156, 2415, 3705, 3039, 337, 2987, 8187, 4224, 3786, 1382, 3124, 9600, 5217, 4027, 5372, 5160, 2067,
      9844
    ],
    entrancement: [
      6801, 6458, 1094, 5343, 8589, 6682, 6988, 7278, 7122, 3904, 2894, 6074, 6574, 6783, 9869, 1830, 6180, 7541, 7872, 3612, 6622, 6377,
      6872, 5643, 3304
    ]
  },
  spaying: {
    unaccommodatingly: [true],
    ungoverned: [
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      false,
      true,
      false,
      false,
      true,
      false,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      false,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      true,
      true,
      false,
      true,
      true,
      true
    ],
    infract: [
      true,
      true,
      false,
      true,
      true,
      true,
      false,
      false,
      true,
      false,
      false,
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      false,
      true,
      true,
      false,
      false,
      true
    ],
    propulsion: [4668, 2825, 2322, 9444, 4778, 2904],
    driblet: [
      true,
      true,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false
    ],
    outdraft: [
      'buzylene',
      'homosystemic',
      'sled',
      'yogoite',
      'meliceris',
      'metachemistry',
      'unaccommodatingly',
      'Ovinae',
      'gotten',
      'burnt',
      'subtriplicated',
      'unprejudicial',
      'overeducate',
      'ganglioid',
      'ovoviviparously',
      'slurbow',
      'fermerer',
      'chromatophilic',
      'nonconcludent',
      'scelerat',
      'scelerat',
      'forthwith',
      'hounding',
      'conceptional',
      'imperence',
      'Delsartean',
      'schistaceous',
      'somniloquy',
      'disturn',
      'Brachiata',
      'Saturnalian',
      'primitivism',
      'chondriomere',
      'aspheterism',
      'sleepify',
      'pentathionic',
      'untwisted',
      'tributyrin',
      'interparietale',
      'scunner',
      'tonguiness',
      'stentoronic'
    ],
    presumptuous: [
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      false,
      true,
      true,
      false,
      true,
      true,
      false,
      false,
      false,
      true
    ],
    precursive: [
      true,
      false,
      false,
      false,
      false,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      false,
      true,
      false,
      true,
      true,
      false,
      false,
      true,
      false,
      false,
      true,
      false,
      false,
      true,
      true,
      true,
      true,
      false,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      false,
      true,
      false,
      false,
      false,
      true,
      true,
      true,
      true
    ],
    Somal: [
      'whitecoat',
      'worldling',
      'asphalt',
      'archagitator',
      'dislodgement',
      'citronade',
      'knotwort',
      'condensedness',
      'kangaroo',
      'enscroll',
      'foliature',
      'aischrolatreia',
      'zig',
      'forcing',
      'Palaeomastodon',
      'pelvisternum',
      'propaedeutical',
      'pointer',
      'environmental',
      'conduplicated',
      'koolah',
      'tupanship'
    ]
  },
  Idiosepiidae: {
    Taal: {
      busher: 'zwitterionic',
      thorax: 'unelementary',
      erased: 'dicatalexis',
      congressionist: false,
      dumpy: 'upher'
    },
    unfailableness: {
      unfructuously: 'grubbiness',
      natricine: 'babblishly',
      hexahydroxy: 5465,
      purchase: false,
      bailer: true,
      adephagan: 'presbyopia',
      trest: false,
      gradient: true,
      ferulic: 'uniovulate',
      redecline: false,
      Birkenhead: 6842
    },
    bluggy: {
      siccity: 7881,
      adephagan: false,
      philophilosophos: 'oxbiter',
      Ashkenazim: false,
      kilocycle: false,
      unentrance: 8183,
      upher: 'Phajus',
      unsurpassableness: 'unenforcedly',
      uninsured: 'Lin',
      squandermania: 60,
      heptitol: 7578,
      omphaloncus: 3933,
      Pyrrhic: 'fountainlet',
      typhic: false,
      eaglewood: true
    },
    empyrean: {
      foundership: 'disafforestation',
      indefinable: true,
      foundery: false,
      decarhinus: 1539,
      anaglyph: 'disturn',
      cuboidal: true,
      monkeyish: true,
      servitude: 4432,
      Yquem: 5814,
      grubbiness: 6996
    },
    adactyl: {
      gotten: true,
      schoolcraft: false,
      dilatingly: 'flyflap',
      underact: 'Saratogan',
      sybaritism: false,
      nonrectangular: 2771,
      unexceptionably: 'unwounded',
      appendicle: true,
      baller: 'dephlegmator',
      Mimulus: 5708,
      interregnum: false,
      breaker: 1981,
      shamefacedly: false,
      bedstring: 9748,
      lifey: 'acetylenediurein',
      Idiosepiidae: false,
      praisefully: true,
      poditic: true
    },
    pharyngotonsillitis: {
      fanon: true,
      bipyridyl: 'metapterygium',
      Saturnalian: 9861,
      unimpenetrable: true,
      Byronic: 'hedgy',
      attainability: false,
      trunkless: 5098,
      paedogenesis: 'unbeing',
      beroll: 'tonga'
    },
    informative: {
      apocodeine: false,
      perfervidness: 'weeze',
      minienize: 'Anselm',
      preventer: true,
      individualize: true,
      acquisitum: false,
      sportsmanlike: 2583,
      attainability: 'inaxon',
      presuperintendence: 'statefulness'
    },
    worriedness: {
      indignance: 7465,
      unhero: 6659,
      supersympathy: true,
      indeformable: 877,
      oxyquinoline: 6559,
      perikronion: 3664
    },
    unrhymed: {
      rumorproof: 2600,
      nerval: 'weeze',
      notarikon: 1067,
      nonrectangular: 7714,
      shamefacedly: false,
      louse: 6262,
      unfructuously: false,
      infract: false,
      underact: 3928
    },
    bridle: {
      histology: 'outdraft',
      rollickingness: true,
      outweary: false,
      fitchee: 'cephalhematoma',
      kettledrummer: 4510,
      ingrowth: 'mandelic'
    },
    reputationless: {
      dumpy: 'cyathium',
      dermobranchiata: 'goatlike',
      subtriplicated: true,
      firetop: false,
      gambet: false,
      inveteracy: 'fountainlet',
      proferment: 'lauder',
      osmometric: false,
      purificator: 'dephlegmator',
      pricklingly: 8434,
      trepidatory: 5962,
      Tanyoan: 50,
      brazilein: 4869
    },
    overscrub: {
      counternoise: 9378,
      deferment: 'Serridentines',
      grama: false,
      soho: true,
      zwitterionic: 256,
      barbiturate: 9926
    },
    personalism: {
      scritch: 6856,
      lupoid: 'Birkenhead',
      weeze: 'esthesiometer',
      basilweed: 'Lecanium',
      stenogastric: 4522,
      beriberic: 'lickspittling',
      psychographic: false,
      principalness: 'kangaroo',
      disafforestation: 'nonliability',
      uncompassionate: true,
      exalate: 'unprejudicial',
      Vaudois: true,
      novelwright: 8213,
      pedigerous: 'typhic',
      oxbiter: 'overaccumulate',
      takosis: 'dandruffy',
      anaglyph: 'sportsmanlike',
      hendecoic: 3158,
      pharyngopathy: false,
      eradicator: 'preimpress',
      Octogynia: 'guttural'
    },
    Atheriogaea: {
      noncoloring: false,
      Austrophilism: false,
      nonimmigrant: 'gambet',
      masting: true,
      quadrumane: 'misexample',
      glossophagine: 'sybaritism',
      disbelief: 9642,
      unrefusingly: 'teleseme',
      psorospermosis: 5494,
      asclepiadeous: false,
      rollickingness: true,
      Palaeomastodon: 'preremove',
      behammer: 'ingrowth',
      blossomtime: false,
      garter: 6135,
      attainability: 6917
    },
    mystificatory: {
      lifey: 'scelerat',
      pentathionic: 'conduplicated',
      nonlover: false,
      kala: 5068,
      ganglioid: true,
      unwounded: 7911,
      hedgy: 1192,
      basos: true,
      Tatary: 'treader',
      heterochronic: 9439,
      cuboidal: 7760,
      coky: true,
      volumescope: 'meteorogram',
      Muncerian: 'outdraft',
      glossophagine: 8216
    },
    whitecoat: {
      obtect: false,
      princeps: 7418,
      minienize: true,
      pointer: true,
      nidologist: 'foundership',
      burroweed: 'trekker',
      facticide: 'atrocity'
    }
  },
  eradicator: {
    disturn: [
      'preadjunct',
      'prewound',
      'surflike',
      'heterochronic',
      'servitude',
      'stentoronic',
      'abbot',
      'indeformable',
      'electroforming',
      'monkeyish',
      'stereophotographic',
      'sixpence',
      'collyrium',
      'conduplicated',
      'tribase',
      'velours',
      'vinelet',
      'keratocentesis',
      'antimycotic',
      'swinehull',
      'adactyl',
      'nidologist',
      'basilweed',
      'obtect',
      'mycomycete',
      'gold',
      'unconfidence',
      'firetop',
      'septated',
      'fractionally',
      'cafeneh',
      'urrhodin',
      'subharmonic',
      'breaker',
      'statefulness',
      'teleseme',
      'dilatingly',
      'prescapula',
      'ornithon',
      'profanely',
      'blameless',
      'guijo',
      'cherubic',
      'bumbaste',
      'iracund',
      'troolie'
    ]
  },
  preindication: {
    apocodeine: {
      Saccobranchiata: true,
      freezer: 'untastable',
      ambry: 'eellike',
      smirchy: 1896,
      whilom: 7849,
      louse: false
    },
    bejel: {
      eradicator: true,
      takosis: false,
      duroquinone: true,
      hecte: false,
      sweatband: true,
      unmackly: false,
      metachemistry: 8668,
      precursive: 'endosalpingitis',
      rollick: true,
      annodated: 'azo',
      unenforcedly: 7182,
      bellite: false,
      glycogelatin: 'Suomic',
      nidologist: 8770
    },
    tart: {
      acroasphyxia: 1104,
      loaferish: 8771,
      mycomycete: 'antu',
      Hafgan: 4319,
      Dyophysitism: 'pentapolis',
      afluking: false,
      kettledrummer: 'Mil',
      underact: 'blameless',
      ophthalmomalacia: 'wildness',
      betso: 9155,
      Actaeon: false,
      outweary: false,
      environmental: false
    },
    Ashkenazim: {
      misexample: 'staghorn',
      cafeneh: 'hammy',
      apportionable: 'roominess',
      wellington: true,
      unoperably: 'undispellable',
      Caesardom: 7510,
      aweary: 'Pentelic',
      azo: 960
    },
    consentiently: {
      grapnel: true,
      monolithic: true,
      evincement: 5779,
      unimpenetrable: 6937,
      imminution: 'Actaeon',
      chimopeelagic: false,
      consentiently: false,
      ateleological: 'nonliability',
      spaying: 'Caesardom'
    },
    shamefacedly: {
      confederationist: false,
      ratable: true,
      carmoisin: 5234,
      psychoanalyzer: false,
      glyceride: 8882,
      mastlike: 'muscose',
      imminution: 'Mimulus',
      studbook: false,
      Hansardization: true,
      Phajus: 1644
    },
    diligentness: {
      trunkless: true,
      xi: 'handcraft',
      nonsetting: false,
      strangling: true,
      inveteracy: true,
      statometer: 'entrancement',
      nonrendition: 'thrombolymphangitis',
      epigenetic: false,
      burroweed: false,
      licentiate: 'periductal'
    },
    scorching: {
      pobs: 'monolithic',
      overeducate: false,
      nonrectangular: 9847,
      Nazariteship: false
    },
    Apneumona: {
      unwist: 7546,
      invective: 5185,
      dodecane: true,
      baba: 3703
    }
  }
};

export const prettyObj = `<Object> {\n  amygdalase: <Object> {\n    peacemaking: Array<number> (44 items) [ \n      65,\n      2016,\n      5251,\n      7071,\n      5726,\n      3325,\n      9893,\n      1547,\n      1409,\n      6715,\n      3656,\n      6780,\n      1460,\n      521,\n      3103,\n      6618,\n      9433,\n      3056,\n      70,\n      4967,\n      3641,\n      6013,\n      9235,\n      1163,\n      1117,\n      4493,\n      1464,\n      4278,\n      4714,\n      4520,\n      7763,\n      2937,\n      4418,\n      1613,\n      8941,\n      7429,\n      7766,\n      5482,\n      9928,\n      3749,\n      4625,\n      1975,\n      4595,\n      3458,\n    ],\n    housewifeliness: Array<string> (18 items) [ \n      'freezer',\n      'hield',\n      'inaxon',\n      'philophilosophos',\n      'Saturnalian',\n      'celery',\n      'forsooth',\n      'nirles',\n      'duteous',\n      'gastrohelcosis',\n      'hateful',\n      'exalate',\n      'scowlingly',\n      'thoracoscopy',\n      'glossophagine',\n      'informative',\n      'indignance',\n      'ophthalmomalacia',\n    ],\n    baller: Array<number> (28 items) [ \n      4497,\n      4151,\n      7362,\n      3155,\n      1098,\n      9372,\n      922,\n      5132,\n      8717,\n      1053,\n      9654,\n      6451,\n      9894,\n      8481,\n      2487,\n      545,\n      6062,\n      1350,\n      1321,\n      9695,\n      7783,\n      6100,\n      6511,\n      4994,\n      6873,\n      5105,\n      3804,\n      4896,\n    ],\n    heterochronic: Array<string> (13 items) [ \n      'somniloquy',\n      'interenjoy',\n      'vastity',\n      'abdominous',\n      'nonimmigrant',\n      'verbomania',\n      'hexastemonous',\n      'hoyle',\n      'plicater',\n      'hygrodeik',\n      'niellated',\n      'extrafoliaceous',\n      'precursive',\n    ],\n    reamer: Array<boolean> (41 items) [ \n      true,\n      false,\n      false,\n      true,\n      true,\n      false,\n      true,\n      false,\n      true,\n      true,\n      true,\n      false,\n      true,\n      false,\n      false,\n      true,\n      false,\n      true,\n      true,\n      false,\n      true,\n      false,\n      false,\n      true,\n      true,\n      true,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      true,\n      true,\n      false,\n      true,\n      false,\n    ],\n  },\n  apagogically: <Object> {\n    troolie: <Object> {\n      preponderance: 'aischrolatreia',\n      warison: 'hydrocycle',\n      meteorogram: 6608,\n      nonporphyritic: 344,\n      scelerat: 5669,\n      rumorproof: true,\n      garawi: 'adactyl',\n      stythe: 8681,\n      primitivism: 'unenforcedly',\n      conjunct: false,\n      schistaceous: 'kilocycle',\n      anthropophagistic: 'seedbox',\n      treacliness: 'ratable',\n    },\n    treader: <Object> {\n      evangelary: 'rattlingly',\n      capersome: 'columnization',\n      saturator: true,\n      forthwith: 4799,\n      metachemistry: true,\n      velours: 6616,\n      dulcifluous: 'spinobulbar',\n      wildness: 'Sid',\n    },\n    Jeremian: <Object> {\n      probeer: 'bombastic',\n      ratable: 9483,\n      pharyngotonsillitis: 6876,\n      homosystemic: 9566,\n      notarikon: 2254,\n      fiduciary: 149,\n      nextly: true,\n      flanched: 1280,\n      Decimus: 1492,\n      humpback: 'Kaibartha',\n    },\n    koolah: <Object> {\n      kettledrummer: false,\n      precondemnation: 750,\n      koolah: 'Madelon',\n      deferment: 'goatlike',\n      unequated: true,\n      nonporphyritic: 3289,\n      azo: 'snary',\n      ringe: 7921,\n      preindication: false,\n      synactic: false,\n      propaedeutical: 6406,\n      glossophagine: 'intermenstruum',\n      warison: 3400,\n      unagile: 6689,\n      undisputed: 'Chaetophoraceae',\n    },\n    bombastic: <Object> {\n      psychoanalyzer: 846,\n      ovoviviparously: false,\n      dilatingly: 5447,\n      capersome: 'subglacially',\n      dihydroxy: 'bufonite',\n    },\n    themeless: <Object> {\n      ironback: false,\n      unpleadable: 5189,\n      unequated: true,\n      licentiate: 5613,\n      collyrium: 'toolmark',\n      acquisitum: 'poststertorous',\n      scorching: 8498,\n      reamer: 'opusculum',\n    },\n    nonpresbyter: <Object> {\n      evincement: true,\n      lemography: 39,\n      perfervidness: 'perceptive',\n      bizet: 'os',\n      adenia: 'nonconcludent',\n      commenceable: true,\n      unprejudicial: 'kala',\n      brachypyramid: 6422,\n      Taal: true,\n    },\n    telemetric: <Object> {\n      dermobranchiata: 'unwounded',\n      sigillarian: true,\n      unrhymed: 5319,\n      extratension: 'Tatary',\n      unbeing: false,\n      enfeeble: 'heterochronic',\n      mutinously: 'exalate',\n      proferment: 'Mil',\n    },\n    hendecoic: <Object> {\n      confederationist: false,\n      nonporphyritic: 'presumptuous',\n    },\n    foremasthand: <Object> {\n      Idiosepiidae: true,\n      primitivism: 'prewound',\n      lifey: 8926,\n      untastable: 9821,\n      nirles: false,\n      vestal: true,\n      introductoriness: 'ventripotential',\n      empyrean: 'Honduran',\n      glottiscope: 5663,\n      oncin: 3319,\n      Phalarism: 5195,\n      sniffly: 'glycogelatin',\n      subglacially: false,\n      zwitterionic: false,\n    },\n  },\n  ratable: <Object> {\n    forsooth: <Object> {\n      dredge: true,\n      overhover: true,\n      force: 'Octavian',\n      mandelic: true,\n      endosalpingitis: 'Kaibartha',\n      dermobranchiata: 'reactivity',\n      rampire: 'esophagotomy',\n      hield: 4808,\n      outferret: false,\n      ethnize: false,\n      plumbum: 4434,\n    },\n    inconvertibility: <Object> {\n      pobs: 'keratocentesis',\n      Saturnalian: true,\n      loaferish: false,\n      overhover: 4857,\n      antimycotic: true,\n      aweary: 7619,\n      Elaps: true,\n      conjunct: false,\n      unchapter: 8078,\n      overdevotedly: 'Octogynia',\n      gold: 'ayelp',\n      Mackinaw: 4912,\n      trepidatory: 4402,\n      Lin: false,\n      breaker: 9271,\n    },\n    unenforcedly: <Object> {\n      foundery: false,\n      ninut: 5313,\n      principalness: 3857,\n      asclepiadeous: false,\n      hierogrammatical: true,\n      glossophagine: true,\n      louse: 'pleocrystalline',\n    },\n    tipstaff: <Object> {\n      capersome: 6136,\n      spydom: 'garawi',\n      epicranial: 8284,\n      scenic: 'spydom',\n      angiolith: true,\n      novelwright: 'basos',\n      asphalt: false,\n      rumorproof: 'natricine',\n      confederationist: false,\n    },\n    Saturnalian: <Object> {\n      roominess: 'stomachlessness',\n      hammy: false,\n      comicocynical: true,\n      proctoclysis: false,\n      caravan: 1042,\n      uncompassionate: 6828,\n      undetermination: 6473,\n      personalism: 8747,\n      tupanship: true,\n      ganglioid: 'subarmor',\n      gold: false,\n      Blackbeard: true,\n    },\n    bombastic: <Object> {\n      unequated: 'loaferish',\n      fitchee: 'discontinuee',\n      dilatingly: 'Pentelic',\n      fusible: 'scoliotic',\n      rollickingness: 'tribase',\n      atamasco: 'unhero',\n      hysteric: true,\n      intenable: false,\n      barbiturate: false,\n      dacryocystotomy: false,\n    },\n    underact: <Object> {\n      acroasphyxia: 'ludefisk',\n      principalness: 'Sisseton',\n      lampers: 'Pygopodidae',\n      purchase: 1843,\n    },\n    complacent: <Object> {\n      hateful: 7358,\n      trapped: false,\n      dulcifluous: true,\n      supersympathy: false,\n      Caesardom: 'anatomicopathologic',\n      bitterroot: 3375,\n      epigenetic: true,\n      macrosymbiont: 1817,\n      noncarnivorous: false,\n      transversomedial: 'lovelorn',\n    },\n    distasteful: <Object> {\n      enfeeble: false,\n      cyanidation: 'tech',\n      iceland: 5707,\n      natricine: false,\n      deiformity: 'toying',\n      archheart: 'milliare',\n      adenology: 6315,\n      ruck: 4703,\n      hateful: 'urrhodin',\n      koku: true,\n      annodated: 'unenforcedly',\n    },\n    anaphylatoxin: <Object> {\n      congressionist: 'echinodermic',\n      slackerism: true,\n      guijo: 102,\n      macrospore: 3789,\n      unjagged: true,\n    },\n    Lecanium: <Object> {\n      ichthyotomy: 'Dardistan',\n      flatwise: false,\n      semisocial: 6342,\n      poststertorous: true,\n      nonumbilicate: 9668,\n      slackerism: 'preaffiliation',\n    },\n    hendecoic: <Object> {\n      pitchometer: 'fanon',\n      amateur: 'cyanidation',\n      amylopsin: false,\n      urethrorrhea: 'baseball',\n      nonconcludent: 5458,\n      imitability: 3953,\n      preindication: 6644,\n      helvite: 7318,\n      humpback: false,\n      planarioid: true,\n      Rajah: false,\n      Caesardom: 'kelty',\n    },\n    eellike: <Object> {\n      menorrhagia: 'zygozoospore',\n      nonliability: false,\n    },\n    fibroplastic: <Object> {\n      sensationistic: 'gradient',\n      loaferish: 'Muncerian',\n      caravan: 5761,\n      supracaudal: 'glycogelatin',\n      lovelorn: 7156,\n      tarnside: true,\n      Eumenes: 'foliature',\n      marshwort: true,\n    },\n  },\n  microdrawing: <Object> {\n    profanely: <Object> {\n      abbot: 1295,\n      recce: 8334,\n      licentiate: 8441,\n      trest: 7223,\n      anaglyph: 9696,\n      foundery: 2346,\n      presbyopia: true,\n    },\n    inconvertibility: <Object> {\n      reputationless: 4969,\n      porwigle: 8549,\n      certifiableness: 4036,\n      dolichocephali: 'unsurpassableness',\n      eater: 6483,\n      elderhood: true,\n      soulfulness: 'sybaritism',\n      oxbiter: true,\n    },\n    torse: <Object> {\n      siccity: true,\n      coky: 'ludefisk',\n      bellite: 'hypodorian',\n      introductoriness: 9914,\n      vesicupapular: 'duteous',\n      pitchometer: true,\n    },\n  },\n  foremasthand: <Object> {\n    extratension: Array<string> (47 items) [ \n      'garter',\n      'Tanyoan',\n      'outweary',\n      'Bonapartism',\n      'milliare',\n      'lifey',\n      'dubitatingly',\n      'pobs',\n      'Serridentines',\n      'nirles',\n      'hereby',\n      'azo',\n      'driblet',\n      'imminution',\n      'dacryocystotomy',\n      'anaphylatoxin',\n      'columnization',\n      'heptitol',\n      'tarnside',\n      'Eumenes',\n      'decoyer',\n      'karyomitoic',\n      'Mil',\n      'Orobanche',\n      'impalpably',\n      'overeducate',\n      'unsteck',\n      'unclassable',\n      'avowably',\n      'zig',\n      'extrafoliaceous',\n      'torse',\n      'antiprohibitionist',\n      'unsurpassableness',\n      'deiformity',\n      'Dioecia',\n      'septated',\n      'underivable',\n      'qualitied',\n      'pharyngopathy',\n      'trekker',\n      'nerval',\n      'outweary',\n      'unbrotherliness',\n      'optotechnics',\n      'Mimulus',\n      'unbumptious',\n    ],\n    Vaudois: Array<number> (36 items) [ \n      7957,\n      5096,\n      7055,\n      2466,\n      3607,\n      9716,\n      4551,\n      1242,\n      1696,\n      1959,\n      9440,\n      336,\n      100,\n      1779,\n      8773,\n      5649,\n      5566,\n      6192,\n      7976,\n      2831,\n      8144,\n      4551,\n      5126,\n      1418,\n      6042,\n      9238,\n      8126,\n      6002,\n      3378,\n      3895,\n      1077,\n      8923,\n      6722,\n      4283,\n      5247,\n      6690,\n    ],\n    poststertorous: Array<boolean> (24 items) [ \n      false,\n      false,\n      false,\n      true,\n      true,\n      true,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n      false,\n      false,\n      true,\n      false,\n      false,\n      false,\n      true,\n      true,\n      false,\n      false,\n      false,\n      true,\n    ],\n    patterny: Array<boolean> (19 items) [ \n      false,\n      false,\n      false,\n      false,\n      false,\n      true,\n      true,\n      true,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n      false,\n      true,\n      true,\n      true,\n      false,\n    ],\n    song: Array<boolean> (15 items) [ \n      false,\n      true,\n      false,\n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n    ],\n    foremasthand: Array<number> (1 items) [ 2678 ],\n    imitability: Array<boolean> (14 items) [ \n      true,\n      false,\n      false,\n      true,\n      true,\n      true,\n      false,\n      true,\n      false,\n      false,\n      true,\n      true,\n      false,\n      false,\n    ],\n    blossomtime: Array<number> (38 items) [ \n      3723,\n      4953,\n      4357,\n      6191,\n      6279,\n      2718,\n      3840,\n      9782,\n      9849,\n      4709,\n      6551,\n      3556,\n      7043,\n      8956,\n      9994,\n      8354,\n      2066,\n      4068,\n      29,\n      9036,\n      3080,\n      4685,\n      3241,\n      535,\n      8006,\n      5560,\n      6890,\n      171,\n      5815,\n      1163,\n      8467,\n      8600,\n      9241,\n      4086,\n      2229,\n      1629,\n      261,\n      8115,\n    ],\n    scorching: Array<number> (21 items) [ \n      5401,\n      2243,\n      674,\n      5497,\n      8439,\n      2049,\n      2455,\n      2705,\n      6030,\n      7062,\n      1346,\n      9389,\n      6719,\n      9027,\n      5,\n      5598,\n      1494,\n      1162,\n      6208,\n      1951,\n      902,\n    ],\n    underivable: Array<boolean> (2 items) [ \n      false,\n      true,\n    ],\n    ateleological: Array<string> (15 items) [ \n      'firetop',\n      'hawserwise',\n      'elaidinic',\n      'psychoanalyzer',\n      'unhandsome',\n      'laryngoscopical',\n      'wellington',\n      'monochlor',\n      'nystagmus',\n      'gambet',\n      'tech',\n      'confederationist',\n      'nonrendition',\n      'diligentness',\n      'unobjective',\n    ],\n    telson: Array<number> (23 items) [ \n      7067,\n      8002,\n      1302,\n      8268,\n      8182,\n      9156,\n      2415,\n      3705,\n      3039,\n      337,\n      2987,\n      8187,\n      4224,\n      3786,\n      1382,\n      3124,\n      9600,\n      5217,\n      4027,\n      5372,\n      5160,\n      2067,\n      9844,\n    ],\n    entrancement: Array<number> (25 items) [ \n      6801,\n      6458,\n      1094,\n      5343,\n      8589,\n      6682,\n      6988,\n      7278,\n      7122,\n      3904,\n      2894,\n      6074,\n      6574,\n      6783,\n      9869,\n      1830,\n      6180,\n      7541,\n      7872,\n      3612,\n      6622,\n      6377,\n      6872,\n      5643,\n      3304,\n    ],\n  },\n  spaying: <Object> {\n    unaccommodatingly: Array<boolean> (1 items) [ true ],\n    ungoverned: Array<boolean> (37 items) [ \n      false,\n      false,\n      true,\n      true,\n      true,\n      true,\n      true,\n      false,\n      true,\n      false,\n      false,\n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      false,\n      true,\n      false,\n      false,\n      true,\n      true,\n      false,\n      true,\n      false,\n      true,\n      false,\n      true,\n      false,\n      false,\n      true,\n      true,\n      false,\n      true,\n      true,\n      true,\n    ],\n    infract: Array<boolean> (24 items) [ \n      true,\n      true,\n      false,\n      true,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n      false,\n      true,\n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      false,\n      true,\n      true,\n      false,\n      false,\n      true,\n    ],\n    propulsion: Array<number> (6 items) [ \n      4668,\n      2825,\n      2322,\n      9444,\n      4778,\n      2904,\n    ],\n    driblet: Array<boolean> (27 items) [ \n      true,\n      true,\n      true,\n      false,\n      false,\n      false,\n      true,\n      false,\n      true,\n      false,\n      false,\n      false,\n      true,\n      true,\n      true,\n      true,\n      true,\n      true,\n      true,\n      true,\n      true,\n      true,\n      false,\n      false,\n      false,\n      false,\n      false,\n    ],\n    outdraft: Array<string> (42 items) [ \n      'buzylene',\n      'homosystemic',\n      'sled',\n      'yogoite',\n      'meliceris',\n      'metachemistry',\n      'unaccommodatingly',\n      'Ovinae',\n      'gotten',\n      'burnt',\n      'subtriplicated',\n      'unprejudicial',\n      'overeducate',\n      'ganglioid',\n      'ovoviviparously',\n      'slurbow',\n      'fermerer',\n      'chromatophilic',\n      'nonconcludent',\n      'scelerat',\n      'scelerat',\n      'forthwith',\n      'hounding',\n      'conceptional',\n      'imperence',\n      'Delsartean',\n      'schistaceous',\n      'somniloquy',\n      'disturn',\n      'Brachiata',\n      'Saturnalian',\n      'primitivism',\n      'chondriomere',\n      'aspheterism',\n      'sleepify',\n      'pentathionic',\n      'untwisted',\n      'tributyrin',\n      'interparietale',\n      'scunner',\n      'tonguiness',\n      'stentoronic',\n    ],\n    presumptuous: Array<boolean> (31 items) [ \n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n      true,\n      false,\n      false,\n      false,\n      true,\n      false,\n      true,\n      false,\n      false,\n      false,\n      false,\n      false,\n      true,\n      false,\n      true,\n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      false,\n      true,\n    ],\n    precursive: Array<boolean> (47 items) [ \n      true,\n      false,\n      false,\n      false,\n      false,\n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n      true,\n      false,\n      true,\n      true,\n      false,\n      false,\n      true,\n      false,\n      false,\n      true,\n      false,\n      false,\n      true,\n      true,\n      true,\n      true,\n      false,\n      true,\n      false,\n      true,\n      false,\n      false,\n      false,\n      true,\n      true,\n      false,\n      true,\n      false,\n      false,\n      false,\n      true,\n      true,\n      true,\n      true,\n    ],\n    Somal: Array<string> (22 items) [ \n      'whitecoat',\n      'worldling',\n      'asphalt',\n      'archagitator',\n      'dislodgement',\n      'citronade',\n      'knotwort',\n      'condensedness',\n      'kangaroo',\n      'enscroll',\n      'foliature',\n      'aischrolatreia',\n      'zig',\n      'forcing',\n      'Palaeomastodon',\n      'pelvisternum',\n      'propaedeutical',\n      'pointer',\n      'environmental',\n      'conduplicated',\n      'koolah',\n      'tupanship',\n    ],\n  },\n  Idiosepiidae: <Object> {\n    Taal: <Object> {\n      busher: 'zwitterionic',\n      thorax: 'unelementary',\n      erased: 'dicatalexis',\n      congressionist: false,\n      dumpy: 'upher',\n    },\n    unfailableness: <Object> {\n      unfructuously: 'grubbiness',\n      natricine: 'babblishly',\n      hexahydroxy: 5465,\n      purchase: false,\n      bailer: true,\n      adephagan: 'presbyopia',\n      trest: false,\n      gradient: true,\n      ferulic: 'uniovulate',\n      redecline: false,\n      Birkenhead: 6842,\n    },\n    bluggy: <Object> {\n      siccity: 7881,\n      adephagan: false,\n      philophilosophos: 'oxbiter',\n      Ashkenazim: false,\n      kilocycle: false,\n      unentrance: 8183,\n      upher: 'Phajus',\n      unsurpassableness: 'unenforcedly',\n      uninsured: 'Lin',\n      squandermania: 60,\n      heptitol: 7578,\n      omphaloncus: 3933,\n      Pyrrhic: 'fountainlet',\n      typhic: false,\n      eaglewood: true,\n    },\n    empyrean: <Object> {\n      foundership: 'disafforestation',\n      indefinable: true,\n      foundery: false,\n      decarhinus: 1539,\n      anaglyph: 'disturn',\n      cuboidal: true,\n      monkeyish: true,\n      servitude: 4432,\n      Yquem: 5814,\n      grubbiness: 6996,\n    },\n    adactyl: <Object> {\n      gotten: true,\n      schoolcraft: false,\n      dilatingly: 'flyflap',\n      underact: 'Saratogan',\n      sybaritism: false,\n      nonrectangular: 2771,\n      unexceptionably: 'unwounded',\n      appendicle: true,\n      baller: 'dephlegmator',\n      Mimulus: 5708,\n      interregnum: false,\n      breaker: 1981,\n      shamefacedly: false,\n      bedstring: 9748,\n      lifey: 'acetylenediurein',\n      Idiosepiidae: false,\n      praisefully: true,\n      poditic: true,\n    },\n    pharyngotonsillitis: <Object> {\n      fanon: true,\n      bipyridyl: 'metapterygium',\n      Saturnalian: 9861,\n      unimpenetrable: true,\n      Byronic: 'hedgy',\n      attainability: false,\n      trunkless: 5098,\n      paedogenesis: 'unbeing',\n      beroll: 'tonga',\n    },\n    informative: <Object> {\n      apocodeine: false,\n      perfervidness: 'weeze',\n      minienize: 'Anselm',\n      preventer: true,\n      individualize: true,\n      acquisitum: false,\n      sportsmanlike: 2583,\n      attainability: 'inaxon',\n      presuperintendence: 'statefulness',\n    },\n    worriedness: <Object> {\n      indignance: 7465,\n      unhero: 6659,\n      supersympathy: true,\n      indeformable: 877,\n      oxyquinoline: 6559,\n      perikronion: 3664,\n    },\n    unrhymed: <Object> {\n      rumorproof: 2600,\n      nerval: 'weeze',\n      notarikon: 1067,\n      nonrectangular: 7714,\n      shamefacedly: false,\n      louse: 6262,\n      unfructuously: false,\n      infract: false,\n      underact: 3928,\n    },\n    bridle: <Object> {\n      histology: 'outdraft',\n      rollickingness: true,\n      outweary: false,\n      fitchee: 'cephalhematoma',\n      kettledrummer: 4510,\n      ingrowth: 'mandelic',\n    },\n    reputationless: <Object> {\n      dumpy: 'cyathium',\n      dermobranchiata: 'goatlike',\n      subtriplicated: true,\n      firetop: false,\n      gambet: false,\n      inveteracy: 'fountainlet',\n      proferment: 'lauder',\n      osmometric: false,\n      purificator: 'dephlegmator',\n      pricklingly: 8434,\n      trepidatory: 5962,\n      Tanyoan: 50,\n      brazilein: 4869,\n    },\n    overscrub: <Object> {\n      counternoise: 9378,\n      deferment: 'Serridentines',\n      grama: false,\n      soho: true,\n      zwitterionic: 256,\n      barbiturate: 9926,\n    },\n    personalism: <Object> {\n      scritch: 6856,\n      lupoid: 'Birkenhead',\n      weeze: 'esthesiometer',\n      basilweed: 'Lecanium',\n      stenogastric: 4522,\n      beriberic: 'lickspittling',\n      psychographic: false,\n      principalness: 'kangaroo',\n      disafforestation: 'nonliability',\n      uncompassionate: true,\n      exalate: 'unprejudicial',\n      Vaudois: true,\n      novelwright: 8213,\n      pedigerous: 'typhic',\n      oxbiter: 'overaccumulate',\n      takosis: 'dandruffy',\n      anaglyph: 'sportsmanlike',\n      hendecoic: 3158,\n      pharyngopathy: false,\n      eradicator: 'preimpress',\n      Octogynia: 'guttural',\n    },\n    Atheriogaea: <Object> {\n      noncoloring: false,\n      Austrophilism: false,\n      nonimmigrant: 'gambet',\n      masting: true,\n      quadrumane: 'misexample',\n      glossophagine: 'sybaritism',\n      disbelief: 9642,\n      unrefusingly: 'teleseme',\n      psorospermosis: 5494,\n      asclepiadeous: false,\n      rollickingness: true,\n      Palaeomastodon: 'preremove',\n      behammer: 'ingrowth',\n      blossomtime: false,\n      garter: 6135,\n      attainability: 6917,\n    },\n    mystificatory: <Object> {\n      lifey: 'scelerat',\n      pentathionic: 'conduplicated',\n      nonlover: false,\n      kala: 5068,\n      ganglioid: true,\n      unwounded: 7911,\n      hedgy: 1192,\n      basos: true,\n      Tatary: 'treader',\n      heterochronic: 9439,\n      cuboidal: 7760,\n      coky: true,\n      volumescope: 'meteorogram',\n      Muncerian: 'outdraft',\n      glossophagine: 8216,\n    },\n    whitecoat: <Object> {\n      obtect: false,\n      princeps: 7418,\n      minienize: true,\n      pointer: true,\n      nidologist: 'foundership',\n      burroweed: 'trekker',\n      facticide: 'atrocity',\n    },\n  },\n  eradicator: <Object> { disturn: Array<string> (46 items) [ \n      'preadjunct',\n      'prewound',\n      'surflike',\n      'heterochronic',\n      'servitude',\n      'stentoronic',\n      'abbot',\n      'indeformable',\n      'electroforming',\n      'monkeyish',\n      'stereophotographic',\n      'sixpence',\n      'collyrium',\n      'conduplicated',\n      'tribase',\n      'velours',\n      'vinelet',\n      'keratocentesis',\n      'antimycotic',\n      'swinehull',\n      'adactyl',\n      'nidologist',\n      'basilweed',\n      'obtect',\n      'mycomycete',\n      'gold',\n      'unconfidence',\n      'firetop',\n      'septated',\n      'fractionally',\n      'cafeneh',\n      'urrhodin',\n      'subharmonic',\n      'breaker',\n      'statefulness',\n      'teleseme',\n      'dilatingly',\n      'prescapula',\n      'ornithon',\n      'profanely',\n      'blameless',\n      'guijo',\n      'cherubic',\n      'bumbaste',\n      'iracund',\n      'troolie',\n    ] },\n  preindication: <Object> {\n    apocodeine: <Object> {\n      Saccobranchiata: true,\n      freezer: 'untastable',\n      ambry: 'eellike',\n      smirchy: 1896,\n      whilom: 7849,\n      louse: false,\n    },\n    bejel: <Object> {\n      eradicator: true,\n      takosis: false,\n      duroquinone: true,\n      hecte: false,\n      sweatband: true,\n      unmackly: false,\n      metachemistry: 8668,\n      precursive: 'endosalpingitis',\n      rollick: true,\n      annodated: 'azo',\n      unenforcedly: 7182,\n      bellite: false,\n      glycogelatin: 'Suomic',\n      nidologist: 8770,\n    },\n    tart: <Object> {\n      acroasphyxia: 1104,\n      loaferish: 8771,\n      mycomycete: 'antu',\n      Hafgan: 4319,\n      Dyophysitism: 'pentapolis',\n      afluking: false,\n      kettledrummer: 'Mil',\n      underact: 'blameless',\n      ophthalmomalacia: 'wildness',\n      betso: 9155,\n      Actaeon: false,\n      outweary: false,\n      environmental: false,\n    },\n    Ashkenazim: <Object> {\n      misexample: 'staghorn',\n      cafeneh: 'hammy',\n      apportionable: 'roominess',\n      wellington: true,\n      unoperably: 'undispellable',\n      Caesardom: 7510,\n      aweary: 'Pentelic',\n      azo: 960,\n    },\n    consentiently: <Object> {\n      grapnel: true,\n      monolithic: true,\n      evincement: 5779,\n      unimpenetrable: 6937,\n      imminution: 'Actaeon',\n      chimopeelagic: false,\n      consentiently: false,\n      ateleological: 'nonliability',\n      spaying: 'Caesardom',\n    },\n    shamefacedly: <Object> {\n      confederationist: false,\n      ratable: true,\n      carmoisin: 5234,\n      psychoanalyzer: false,\n      glyceride: 8882,\n      mastlike: 'muscose',\n      imminution: 'Mimulus',\n      studbook: false,\n      Hansardization: true,\n      Phajus: 1644,\n    },\n    diligentness: <Object> {\n      trunkless: true,\n      xi: 'handcraft',\n      nonsetting: false,\n      strangling: true,\n      inveteracy: true,\n      statometer: 'entrancement',\n      nonrendition: 'thrombolymphangitis',\n      epigenetic: false,\n      burroweed: false,\n      licentiate: 'periductal',\n    },\n    scorching: <Object> {\n      pobs: 'monolithic',\n      overeducate: false,\n      nonrectangular: 9847,\n      Nazariteship: false,\n    },\n    Apneumona: <Object> {\n      unwist: 7546,\n      invective: 5185,\n      dodecane: true,\n      baba: 3703,\n    },\n  },\n}`;
